FROM node:16.19-alpine

RUN apk update && apk upgrade
RUN apk --no-cache add curl
RUN apk add make g++ python3 git 
RUN npm i -g node-pre-gyp

RUN mkdir /app
WORKDIR /app

COPY package*.json .

RUN npm i
RUN npm i -g serve

COPY src ./src
COPY public ./public
COPY tsconfig.json .

ARG REACT_APP_GRAPHQL_API_URL
ENV REACT_APP_GRAPHQL_API_URL ${REACT_APP_GRAPHQL_API_URL}
ARG REACT_APP_SCREENSHOT_API
ENV REACT_APP_SCREENSHOT_API ${REACT_APP_SCREENSHOT_API}

RUN npm run build

CMD serve -s build