services:
  server:
    restart: always
    build: ./server
    ports:
      - 4000:4000
      - 4001:4001
    volumes:
      - ./server/src:/app/src
  client:
    restart: always
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/app/src