query getProfile {
 profile {
    id
    name
    email
    premium
    role
    pages {
      id
      url
      intervale
      histories {
        id
        status
        date
        responseTime
        screenshot
      }
    }

  }
}