name: e2e-tests

on: pull_request

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Make envfile server
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_JWT_PRIVATE_KEY: zeyfgzeigfyzegfyuzegf
          envkey_NODE_ENV: "development"
          envkey_CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://localhost:4000"
          envkey_SERVER_HOST: "localhost"
          envkey_SERVER_PORT: "4000"
          envkey_DB_HOST: localhost
          envkey_DB_PORT: 5432
          envkey_DB_USER: postgres
          envkey_DB_PASS: postgres
          envkey_DB_NAME: postgres
          directory: server
          file_name: .env
      - name: Make envfile client
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_REACT_APP_GRAPHQL_API_URL: http://localhost:4000
          directory: client
          file_name: .env
      - name: Run e2e tests
        run: npm run e2e-tests